
export const DEFAULT_COLUMNS = [
  { key: 'originalAddress', label: '주소(입력)', enabled: true, order: 1 },
  { key: 'roadAddr', label: '도로명주소', enabled: true, order: 2 },
  { key: 'jibunAddr', label: '지번주소', enabled: false, order: 3 },
  { key: 'sigunguCd', label: '시군구코드', enabled: false, order: 4 },
  { key: 'bjdongCd', label: '법정동코드', enabled: false, order: 5 },
  { key: 'bun', label: '번', enabled: false, order: 6 },
  { key: 'ji', label: '지', enabled: false, order: 7 },
  { key: '건물명', label: '건물명', enabled: true, order: 8 },
  { key: '총연면적', label: '총 연면적(㎡)', enabled: true, order: 9 },
  { key: '연면적', label: '주건축물 연면적(㎡)', enabled: false, order: 10 },
  { key: '부속건축물면적', label: '부속건축물 연면적(㎡)', enabled: false, order: 11 },
  { key: '대지면적', label: '대지면적', enabled: false, order: 12 },
  { key: '건축면적', label: '건축면적', enabled: false, order: 13 },
  { key: '구조코드명', label: '구조', enabled: false, order: 14 },
  { key: '주용도코드명', label: '주용도', enabled: true, order: 15 },
  { key: '지상층수', label: '지상층수', enabled: false, order: 16 },
  { key: '지하층수', label: '지하층수', enabled: false, order: 17 },
  { key: '사용승인일', label: '사용승인일', enabled: true, order: 18 },
  { key: '상태', label: '상태', enabled: true, order: 19 },
  { key: 'message', label: '비고', enabled: true, order: 20 }
];

export const BUILDING_FIELD_MAPPING: { [key: string]: string } = {
  mgmBldrgstPk: '건축물대장_고유번호',
  bldNm: '건물명',
  newPlatPlc: '도로명주소',
  platPlc: '지번주소',
  platArea: '대지면적',
  archArea: '건축면적',
  bcRat: '건폐율',
  totArea: '연면적',
  mainAtchBldArea: '주부속건축물면적',
  atchBldArea: '부속건축물면적',
  vlRat: '용적률',
  strctCdNm: '구조코드명',
  mainPurpsCdNm: '주용도코드명',
  grndFlrCnt: '지상층수',
  ugrndFlrCnt: '지하층수',
  useAprDay: '사용승인일',
  hhldCnt: '세대수',
  fmlyCnt: '가구수',
  totPkngCnt: '총주차수'
};
